import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  // smartphones
  {
    _id: uuid(),
    title: "Iphone 13",
    description: "Apple Iphone 13 256GB",
    categoryName: "smartphones",
    brand: "apple",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/smartphone/iphone.jpg",
    imgAlt: "iphone 13",
    price: 89000,
    discount: 10,
    discountPrice: 80100,
    inStock: true,
    rating: 4,
    allRating: 500,
  },
  {
    _id: uuid(),
    title: "One Plus Nord 2",
    description: "One Plus Nord 2 128GB",
    categoryName: "smartphones",
    brand: "one plus",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/smartphone/oneplus.jpg",
    imgAlt: "oneplus nord",
    price: 25000,
    discount: 15,
    discountPrice: 21250,
    inStock: true,
    rating: 3,
    allRating: 500,
  },
  {
    _id: uuid(),
    title: "Samsung S20 FE",
    description: "Samsung S20 FE 256GB",
    categoryName: "smartphones",
    brand: "samsung",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/smartphone/samsung.jpg",
    imgAlt: "samsung s20",
    price: 59000,
    discount: 10,
    discountPrice: 53100,
    inStock: true,
    rating: 4,
    allRating: 500,
  },
  {
    _id: uuid(),
    title: "Redmi Note 11T",
    description: "Redmi Note 11T 256 GB",
    categoryName: "smartphones",
    brand: "redmi",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/smartphone/xiaomi.jpg",
    imgAlt: "redmi note11",
    price: 14900,
    discount: 10,
    discountPrice: 13410,
    inStock: true,
    rating: 3,
    allRating: 500,
  },
  // Laptop
  {
    _id: uuid(),
    title: "MacBook Air M1",
    description: "MacBook 8GB RAM, 256GB SSD",
    categoryName: "laptop",
    brand: "apple",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/laptop/Apple%20MacBook%20Air%20M1.jpg",
    imgAlt: "apple macbook air ",
    price: 83000,
    discount: 10,
    discountPrice: 74700,
    inStock: true,
    rating: 5,
    allRating: 500,
  },
  {
    _id: uuid(),
    title: "Asus E410KA-EK001W",
    description: "Asus 4GB RAM, 256GB SSD",
    categoryName: "laptop",
    brand: "asus",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/laptop/Asus%20E410KA-EK001W.jpg",
    imgAlt: "asus E410KA",
    price: 27000,
    discount: 5,
    discountPrice: 25650,
    inStock: true,
    rating: 3,
    allRating: 500,
  },
  {
    _id: uuid(),
    title: "HP Pavilion 14",
    description: "HP dv1000TU 8GB RAM",
    categoryName: "laptop",
    brand: "hp",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/laptop/HP%20Pavilion%2014-dv1000TU.jpg",
    imgAlt: "hp Pavilion",
    price: 61900,
    discount: 10,
    discountPrice: 55710,
    inStock: true,
    rating: 4,
    allRating: 500,
  },
  {
    _id: uuid(),
    title: "Lenovo Legion 5",
    description: "16GB RAM, 1TB SSD RTX 3060",
    categoryName: "lenovo",
    brand: "lenovo",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/laptop/Lenovo%20Legion%205.jpg",
    imgAlt: "lenovo lenovo",
    price: 81000,
    discount: 10,
    discountPrice: 72900,
    inStock: true,
    rating: 4,
    allRating: 500,
  },
  // Camera
  {
    _id: uuid(),
    title: "Nikon D780",
    description: "Nikon25.28 MP DSLR Camera",
    categoryName: "lenovo",
    brand: "lenovo",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/camera/Nikon%20D780.jpg",
    imgAlt: "lenovo lenovo",
    price: 45000,
    discount: 5,
    discountPrice: 42750,
    inStock: true,
    rating: 4,
    allRating: 500,
  },
  {
    _id: uuid(),
    title: "Fujifilm Mirrorless",
    description: "Fujifilm  24.2MP 15-45mm Lens",
    categoryName: "camera",
    brand: "Fujifilm",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/camera/Fujifilm%2024.2MP.jpg",
    imgAlt: "lenovo lenovo",
    price: 59000,
    discount: 15,
    discountPrice: 50150,
    inStock: true,
    rating: 2,
    allRating: 500,
  },
  {
    _id: uuid(),
    title: "Canon EOS 1500D",
    description: "24.1MP DSLR Camera",
    categoryName: "camera",
    brand: "canon",
    imgURL:
      "https://raw.githubusercontent.com/ianuragsharma/hostedIMG/main/ecommerce/productIMG/camera/Canon%20EOS.jpg",
    imgAlt: "canon camera",
    price: 37995,
    discount: 15,
    discountPrice: 32295,
    inStock: true,
    rating: 4,
    allRating: 500,
  },
];
